---
- name: list1
  hosts: a1
  tasks: 
    - name: Install a list of packages with a list variable
      ansible.builtin.yum:
        name: "{{ packages }}"
      vars:
        packages:
          - httpd
          - httpd-tools
